[project]
name = "fifa20backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.133.0",
    "joblib>=1.5.3",
    "streamlit>=1.54.0",
]
